
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package backend.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos1 {
  /* terminals */
  public static final int CerrarCorchetes = 6;
  public static final int justifiedC = 57;
  public static final int navy = 69;
  public static final int Menos = 12;
  public static final int Coma = 9;
  public static final int stringg = 38;
  public static final int forr = 29;
  public static final int MenorQue = 18;
  public static final int Porcentaje = 80;
  public static final int AbrirCE = 4;
  public static final int booleann = 39;
  public static final int AA = 62;
  public static final int disc = 60;
  public static final int TextoEComillas = 83;
  public static final int DosPuntos = 26;
  public static final int Variable = 15;
  public static final int Mas = 11;
  public static final int Asterisco = 14;
  public static final int rightC = 56;
  public static final int DiferenteDe = 23;
  public static final int num1 = 61;
  public static final int SEMenorQue = 44;
  public static final int elsee = 33;
  public static final int thenn = 31;
  public static final int CerrarCE = 5;
  public static final int silver = 76;
  public static final int CerrarParentesis = 8;
  public static final int lime = 71;
  public static final int begin = 35;
  public static final int andd = 28;
  public static final int MenorIgual = 22;
  public static final int centerC = 54;
  public static final int ErrorLexico = 2;
  public static final int whilee = 37;
  public static final int orr = 20;
  public static final int green = 74;
  public static final int PuntoYComa = 27;
  public static final int end = 30;
  public static final int circle = 58;
  public static final int MayorQue = 17;
  public static final int Asignacion = 25;
  public static final int SEAmpersand = 46;
  public static final int aqua = 78;
  public static final int red = 66;
  public static final int truee = 32;
  public static final int teal = 65;
  public static final int SEu = 51;
  public static final int SEo = 50;
  public static final int iff = 19;
  public static final int SEn = 53;
  public static final int maroon = 68;
  public static final int square = 59;
  public static final int MayorIgual = 21;
  public static final int white = 73;
  public static final int SEi = 49;
  public static final int EOF = 0;
  public static final int yellow = 77;
  public static final int blue = 67;
  public static final int SEe = 48;
  public static final int Numero = 16;
  public static final int black = 63;
  public static final int SEa = 47;
  public static final int AbrirCorchetes = 3;
  public static final int Hexa = 81;
  public static final int gray = 70;
  public static final int SEMayorQue = 45;
  public static final int error = 1;
  public static final int too = 24;
  public static final int AbrirParentesis = 7;
  public static final int TextoTLink = 82;
  public static final int SEN = 52;
  public static final int Comillas = 43;
  public static final int valorEntero = 79;
  public static final int integerr = 40;
  public static final int purple = 75;
  public static final int printt = 34;
  public static final int leftC = 55;
  public static final int Diagonal = 13;
  public static final int falsee = 36;
  public static final int olive = 64;
  public static final int Igual = 10;
  public static final int var = 41;
  public static final int TextoEComilla = 42;
  public static final int fuchsia = 72;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ErrorLexico",
  "AbrirCorchetes",
  "AbrirCE",
  "CerrarCE",
  "CerrarCorchetes",
  "AbrirParentesis",
  "CerrarParentesis",
  "Coma",
  "Igual",
  "Mas",
  "Menos",
  "Diagonal",
  "Asterisco",
  "Variable",
  "Numero",
  "MayorQue",
  "MenorQue",
  "iff",
  "orr",
  "MayorIgual",
  "MenorIgual",
  "DiferenteDe",
  "too",
  "Asignacion",
  "DosPuntos",
  "PuntoYComa",
  "andd",
  "forr",
  "end",
  "thenn",
  "truee",
  "elsee",
  "printt",
  "begin",
  "falsee",
  "whilee",
  "stringg",
  "booleann",
  "integerr",
  "var",
  "TextoEComilla",
  "Comillas",
  "SEMenorQue",
  "SEMayorQue",
  "SEAmpersand",
  "SEa",
  "SEe",
  "SEi",
  "SEo",
  "SEu",
  "SEN",
  "SEn",
  "centerC",
  "leftC",
  "rightC",
  "justifiedC",
  "circle",
  "square",
  "disc",
  "num1",
  "AA",
  "black",
  "olive",
  "teal",
  "red",
  "blue",
  "maroon",
  "navy",
  "gray",
  "lime",
  "fuchsia",
  "white",
  "green",
  "purple",
  "silver",
  "yellow",
  "aqua",
  "valorEntero",
  "Porcentaje",
  "Hexa",
  "TextoTLink",
  "TextoEComillas"
  };
}

